### ISSUE TITLE
Wrong uuid

### ISSUE THREAD

**Issue by Dmitriy-U** [Bastion-RND/school-lab#21]
There is a repeated uuid in *Physiology* laboratory specification (5104). Maybe it is mistake, because *Biology* (5103) have the same uuid.

> Reference:
> - [5103](https://github.com/Bastion-RND/school-lab/blob/develop/specifications/5104.spec.json#L3)
> - [5103](https://github.com/Bastion-RND/school-lab/blob/develop/specifications/5103.spec.json#L3)

**Comment by ArtyomSkorobogatov** [comment]
уточню у @sergio-rudenko

**Comment by ArtyomSkorobogatov** [comment]
fixed in https://github.com/Bastion-RND/school-lab/commit/b4a4cb5195632e96a5caea7f38a8b66eb60d280e
